### ISSUE TITLE
Upgrade ember-concurrency to version 2.x

### ISSUE THREAD

**Issue by davideferre** [sandydoo/ember-google-maps#101]
I've problems using the new ember-concurrency task modifiers as you can see in [this issue](https://github.com/machty/ember-concurrency/issues/416).
Is it possible to upgrade the `ember-concurrency` dependency to 2.x version?

**Comment by sandydoo** [comment]
Thanks for letting me know, @davideferre! Version `3.3.1` should resolve the issue for you.

**Comment by davideferre** [comment]
> Thanks for letting me know, @davideferre! Version `3.3.1` should resolve the issue for you.

Thank you so much, I'll try the new version today.
