### ISSUE TITLE
Autocomplete is not restricting to a country

### ISSUE THREAD

**Issue by ylsujata** [sandydoo/ember-google-maps#12]
I am trying to use the autocomplete component and even though I am passing region as 'US' it still returns results from all over the world. As I look further it seems Autocomplete needs to be restricted using componentRestrictions.
eg:-
var options = {
  types: ['(places)'],
  componentRestrictions: {country: 'US'}
};

autocomplete = new google.maps.places.Autocomplete(input, options);

Please can you check this out and fix it for us

**Comment by sandydoo** [comment]
If `componentRestrictions` is a valid option, pass it as an argument. Every argument that isn't whitelisted in the docs (no docs for autocomplete for the moment) is passed to the Google Maps component. Every component in this addon works this way. For example:

```js
// Somewhere in a controller or component.
myCountryRestrictions: { country: 'US' }
```

```hbs
{{#g-map ... as |g|}}
  {{g.autocomplete componentRestrictions=myCountryRestrictions}}
{{/g-map}}
```

Check out the docs on contextual components to learn how options are handled.
https://ember-google-maps.sandydoo.me/docs/components
