### ISSUE TITLE
pauseTestForIdle function causes tests failing with timeout

### ISSUE THREAD

**Issue by sinankeskin** [sandydoo/ember-google-maps#132]
Hi. Thank you for this great addon.

With latest version, on **test** environment this function never resolves and in our case, some of our tests are failing with timeout.

https://github.com/sandydoo/ember-google-maps/blob/b18c3ab6fda1b34f64cd210ca9133485714def94/addon/components/g-map.js#L98

If I remove this function and invokes in your code, tests are starting to pass but I'm seeing warnings this time like `InfoWindow.open called without map` etc...

Thanks.

**Comment by sandydoo** [comment]
Hi, @sinankeskin, could you share an example of one of your failing tests? Or a reproduction?

**Comment by sinankeskin** [comment]
I don't think I can share an example but I'll try to fix and create a PR when I have a free time @sandydoo 

Thanks.

**Comment by sandydoo** [comment]
> I don't think I can share an example but I'll try to fix and create a PR when I have a free time @sandydoo

Alright, but keep in mind that I can't merge a PR unless the issue it's fixing can be reproduced.

**Comment by sinankeskin** [comment]
I found the issue.

We're also using [ember-place-autocomplete](https://github.com/dmuneras/ember-place-autocomplete) and your addon and this addon uses different techniques to load google maps js file and this creates a problem but I can confirm this problem is ember-place-autocomplete's problem.

Thank you again for this great addon @sandydoo
