### ISSUE TITLE
Change in region stops map rendering.

### ISSUE THREAD

**Issue by njmalinga** [sandydoo/ember-google-maps#14]
Hi, I'm an ember js developer from South Africa and I really like this addon but it doesn't seem to show the map as soon as I change the region to ZA. Is there a way for it work with ZA or is it not supported?

**Comment by sandydoo** [comment]
@njmalinga, I can't offer advice if I can't reproduce the issue or at least see the code. It would be nice to see relevant excerpts from your `environment.js` config, relevant sample code, and any error messages you're getting in the browser's console. 

The `ZA` region works fine and I have not yet experienced issues with region handling. I would suggest you follow the guide to [getting started](https://ember-google-maps.sandydoo.me/docs/getting-started) and [creating the map](https://ember-google-maps.sandydoo.me/docs/map). You must – at the bare minimum – provide an API `key` and style your map canvas.

**Comment by njmalinga** [comment]
@sandydoo  below is a snippet of my environment.js

ENV['ember-google-maps'] = {
    key: process.env.GOOGLE_MAPS_API_KEY,
    language: 'en',
    region: 'ZA',
    protocol: 'https',
    version: '3.31',
    libraries: ['geometry', 'places']
  }
I may have not conveyed my message properly. I do not get any errors on my browser console however it just shows a blue screen and not the actual map. Soon as I change it back to GB and alter the lat lng accordingly it works
![image](https://user-images.githubusercontent.com/19988892/39840930-6fe5be18-53e1-11e8-8928-874dbdc59e70.png)

**Comment by sandydoo** [comment]
What exactly do you mean by `and alter the lat lng accordingly it works`? Are you sure you're not just in the middle of the ocean in the screenshot? Once again, you can really speed up the process by just posting all the necessary code to replicate this.

As an aside, you don't need to load `libraries: ['geometry', 'places']` unless you actually need those libraries.

**Comment by njmalinga** [comment]
@sandydoo I'm so sorry for taking up so much of your time already. It turns out my coordinates were incorrect. Thanks once again, sorry I wasted your time over nothing.

**Comment by njmalinga** [comment]
its loading the map just fine
![image](https://user-images.githubusercontent.com/19988892/39842458-bd4d1f34-53e6-11e8-9fd4-d422b0161153.png)

**Comment by sandydoo** [comment]
@njmalinga, no problem. Happy you got it sorted out!
