### ISSUE TITLE
Google Distance To

### ISSUE THREAD

**Issue by ChristopherJohnson25** [sandydoo/ember-google-maps#15]
Great add on. One question, does this have 'Distance To' functionality built in? 

I'd like to measure the distance to one point from another. Not sure if I missed it on the docs or not, but a point in the right direction would be helpful. Here's some info..

[https://developers.google.com/maps/documentation/distance-matrix/intro](https://developers.google.com/maps/documentation/distance-matrix/intro)

This codepen is basically doing what I want..

[https://codepen.io/youfoundron/pen/GIlvp](https://codepen.io/youfoundron/pen/GIlvp
)

thank you!!

**Comment by sandydoo** [comment]
No, but it doesn't have to be built in. This addon provides a `googleMapsApi` service which asynchronously loads the `google.maps` API. So if you wanted to access the `distanceMatrix` service, you would wait for `google` to load and initialise the service.

```js
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';

export default Controller.extend({
  googleMapsApi: service(),
  
  init() {
    this._super(...arguments);

    this.get('googleMapsApi.google').then((google) => {
      let distanceMatrixService = new google.maps.DistanceMatrixService();
      // Use or save the service
    });
  }
})
```

You can also use `read` if you need to access `google` often.

```js
import { reads } from '@ember/object/computed';

// ...

google: reads('googleMapsApi.google')
```

If you want a neater solution, you can explore the code used to add the [`directionsService`](https://github.com/sandydoo/ember-google-maps/blob/master/addon/services/google-maps-api.js#L25-L32).

The docs should probably have a whole section on the service...

**Comment by ChristopherJohnson25** [comment]
Perfect! Will take a look soon and implement, thanks a lot!
