### ISSUE TITLE
Setting PlaceTypes for Autocomplete

### ISSUE THREAD

**Issue by ylsujata** [sandydoo/ember-google-maps#18]
Hi,

O am trying to restrict autocomplete to list only allowed types eg:- geocode, addresses etc. How can I pass these values- https://developers.google.com/places/supported_types

Thank you in advance,
Sujata Yellaepeddi

**Comment by sandydoo** [comment]
Most arguments passed to a component are used as options for the map component. The options for each component are not hardcoded into this addon. [Read the addon docs](https://ember-google-maps.sandydoo.me/docs/components) for more details.

Knowing that, this becomes an exercise in reading the Google Maps documentation. [According to the reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/places-widget#Autocomplete), the option you are looking for is `types`.

Let's limit the search to cities only.

```js
types: ['(cities)']
```

```hbs
{{g.autocomplete types=types onSearch=(action "search")}}
  <input type="text">
{{/g.autocomplete}}
```

**Comment by ylsujata** [comment]
That seems to be a good solution. Do I need to update the addon? or will it be working in its current state
