### ISSUE TITLE
Quick Question: Traffic Layers

### ISSUE THREAD

**Issue by joegaudet** [sandydoo/ember-google-maps#186]
Hey just curious the right way to add a traffic layer to maps.

**Comment by sandydoo** [comment]
There's a [section in the docs](https://ember-google-maps.sandydoo.me/docs/advanced) that covers adding custom components.

Create a new component. For example, `app/components/traffic-layer.js`:

```js
import TypicalMapComponent from 'ember-google-maps/components/g-map/typical-map-component';

export default class TrafficLayer extends TypicalMapComponent {
  get name() {
    return 'trafficLayers';
  }

  newMapComponent(options = {}) {
    return new google.maps.TrafficLayer();
  }
}
```

Add your component to `ember-cli-build.js`:

```js
'ember-google-maps': {
  customComponents: {
    // The key is the name you'd like to use in your templates.
    //
    // The value is the name of the component — the same name you'd pass
    // to the component helper.
    trafficLayer: 'traffic-layer',
  },
},
```

You can now use it inside `GMap`:

```hbs
<GMap
  @lat={{...}}
  @lng={{...}}
  @zoom={{12}} as |g|>

  <g.trafficLayer />

</GMap>
```

**Comment by joegaudet** [comment]
Awesome, thank you so much!

**Comment by joegaudet** [comment]
Hrm, seems to be raising an exception.

```
runtime.js:1344 Uncaught Error: Attempted to resolve `template`, which was
expected to be a component, but nothing was found.
    at runtime.js:1344:17
    at reference.js:121:35
    at track (validator.js:709:5)
    at valueForRef (reference.js:120:26)
    at reference.js:199:38
    at reference.js:121:35
    at track (validator.js:709:5)
    at valueForRef (reference.js:120:26)
    at reifyNamed$1 (runtime.js:1822:31)
    at runtime.js:6728:26
```


Environment.js
```

```

sf/logistics/order-map/traffic-map/component.js    'ember-google-maps': {
      key: '', // Using .env files in this example
      language: 'en',
      region: 'GB',
      protocol: 'https',
      version: '3.41',
      libraries: ['geometry', 'places'], // Optional libraries
      // client: undefined,
      // channel: undefined,
      // baseUrl: '//maps.googleapis.com/maps/api/js',
      // mapIds: ['1234', '2345'],
      customComponents: {
        // The key is the name you'd like to use in your templates.
        //
        // The value is the name of the component — the same name you'd pass
        // to the component helper.
        trafficLayer: 'sf/logistics/order-map/traffic-map'
      }
    },
```
import TypicalMapComponent from
'ember-google-maps/components/g-map/typical-map-component';

export default class TrafficLayer extends TypicalMapComponent {
  get name() {
    return 'trafficLayers';
  }

  newMapComponent(options = {}) {
    return new google.maps.TrafficLayer(options.map);
  }
}
```

**Comment by joegaudet** [comment]
Oh these versions:
"ember-source": "~3.28.8",
"ember-google-maps": "^7.0.0"

**Comment by joegaudet** [comment]
Ignore me, the component name didn't line up.

**Comment by joegaudet** [comment]
Hrm, scratch that, error still showing up.

**Comment by sandydoo** [comment]
I tested the above before posting. Try not passing the map to the traffic layer. That's done by the map component at the appropriate time.

`customComponents` needs to be set in `ember-cli-build.js`, not your env. I can't tell whether that's the case from what you posted.

**Comment by joegaudet** [comment]
I tried moving it to ember-cli-build, was in environment.js (my bad), the
error still persists.

I also tried moving the component to the top level of the components
folder, didn't work.

Is it possible that my using of pods could be causing the issue?

.joe

**Comment by joegaudet** [comment]
Are the any other approaches I could take? I just need a handle on the map
component and I can instantiate the traffic layer by hand.

**Comment by joegaudet** [comment]
Based on the error I'm going to guess it's this thing it's having trouble
with:

https://github.com/sandydoo/ember-google-maps/blob/main/addon/components/g-map.hbs#L19

Since it says it cannot find the 'template' component?

Is there perhaps something that's missing or a version of ember I should be
on?
