### ISSUE TITLE
@ember/test-helpers is used in bundled code but is not a dependency

### ISSUE THREAD

**Issue by glenn-vandeputte** [sandydoo/ember-google-maps#196]
### Describe the bug

W

### Expected behaviour

When running tests in a relatively recent ember app I got the error that `@ember/test-helpers` is used or required but not included in dependencies. It is included in the `devDependencies` , but those are not bundled / exposed to consuming applications. I think just moving it to dependencies (as is `@ember/test-waiters`) would fix the issue. 

### Additional context

--------------------------------------------------------------------------------

### Addon configuration and device details

**Addon configuration**:

 - Addon version: [e.g. 1.1]
 
 - Addon config from `environment.js` (**do not** post your API key): 
 
 - Google Maps version: [e.g. 3.31]
 
**Desktop:**
 
 

**Smartphone:**

**Comment by sandydoo** [comment]
Fixed in #197.
