### ISSUE TITLE
Draw on Map

### ISSUE THREAD

**Issue by ivanhueso** [sandydoo/ember-google-maps#29]
Is there a way to add the Circle or Polygono Search where you draw on the map and it search based on your selection?

**Comment by sandydoo** [comment]
Sure, but you'll have to implement that yourself in javascript, i.e. there's not built-in end-to-end solution. The `onLoad` hook will be your friend as it returns the instantiated `map` object.

We may be able to provide some built-in drawing tools as a separate addon at some point, see https://github.com/sandydoo/ember-google-maps/issues/1.
