### ISSUE TITLE
Addon gotcha: instance.on('willDestroyElement') calls too soon

### ISSUE THREAD

**Issue by acorncom** [sandydoo/ember-google-maps#39]
Hey @sandydoo, I'm back again 😉 I've been building a geoJson setup for a client using an addon that hooks into the addon system. Works great for almost everything I need.

But I'm hitting a snag around `willDestroyElement` and removing items from the main map using an addon and public api. Specifically, in a scenario where I do this:

```
{{#g-map ... as |g|}}
  {{#each plots as |plot|}}
    {{g.data feature=plot.feature}}
  {{/each}}
{{/g-map}}
```

Things work great on setup (there's a bunch of hand-waving here around `plot.feature`, but things are working there). Where I'm running into issues is if I remove a plot from the `plots` array and want it removed from the map.

In my `g.data` component, I've got code much akin to this:

```
export default MapComponent.extend({
  ...

  _type: 'data',
  _feature: undefined,

  _addComponent() {
    const map = this.get('publicAPI.map');
    this.set('_feature', map.data.add(this.get('feature'));
  },

  ...

  willDestroyElement() {
    let map = this.get('map');

    // would like to move to this usage. But requires changes to the proxy class in order to support it
    // const map = this.get('publicAPI.map');
    map.data.remove(this.get('_feature'));

    this._super(...arguments);
  }
});
```

This all works (and works well). But I'd like to be sticking to the straight and narrow and uses a call to `this.get('publicAPI.map')` instead as I unload a given feature from the map. However ...

What I'm hitting is that the registration of `publicAPI` that occurs in the [`MapComponent#init` hook](https://github.com/sandydoo/ember-google-maps/blob/master/addon/components/g-map/map-component.js#L43) leads to the publicAPI [`instance.on('willDestroyElement')`](https://github.com/sandydoo/ember-google-maps/blob/master/addon/utils/public-api.js#L29-L31) event handler being called prior to the `willDestroyElement` method I'm setting up myself.

I've temporarily wired around this by using the internal `this.get('map')` call, but would like to stick to using what you've clearly asked me to 😉 I'll push up a PR with a suggested change, but would love to hear your thoughts here ...

**Comment by acorncom** [comment]
Hmm, on revisiting https://github.com/sandydoo/ember-google-maps/blob/master/index.js#L95, I may be mis-reading things. Would you consider `map` an essential part of what addons will always be passed? Seems somewhat logical ... 😉  If so, I can close everything up here ...

**Comment by sandydoo** [comment]
@Hey @acorncom, you can indeed rely on components receiving `map`. I want to get rid of the `on` hook, so I might merge your PR. I will eventually get rid of that whole `publicAPI` class though and replace it with straightforward object composition. It'll be easier to convert to typescript too.

**Comment by acorncom** [comment]
Sounds good, will close this then. Thx!
