### ISSUE TITLE
Update Feature Comparison Table

### ISSUE THREAD

**Issue by Matt-Jensen** [sandydoo/ember-google-maps#4]
Great work on this Addon!

You may know me as the reluctant author of [ember-cli-g-maps](https://github.com/Matt-Jensen/ember-cli-g-maps). I just wanted to let you know I've just added a deprecation notice to my addon, which recommends usage of this project instead.  While you may wish to keep the feature comparison table of ember-cli-g-maps, it might also be unnecessary to invite the comparison at this point.  Anyway this is more of an FYI, obviously it's your call.

**Comment by sandydoo** [comment]
Thanks, @Matt-Jensen. I've removed the section entirely and have replaced it with a more reasonable list of features instead.
