### ISSUE TITLE
No way to get overlay's OverlayView instance (mapComponent)

### ISSUE THREAD

**Issue by HodofHod** [sandydoo/ember-google-maps#42]
While other components expose their `mapComponent` as the `target` of the object passed into event handlers, overlay is the exception, because the `target` is the HTMLElement. 

There seems to be no public way to get access to the `OverlayView` class instance for `g-map/overlay` components.

**Comment by sandydoo** [comment]
@HodofHod, the documentation hasn't been updated to explain this. There is no guarantee that `target` == `mapComponent`. Each event now returns an object with a bunch of useful things: the browser event, the Google Maps version of the event, the event target, the map instance, and the component's `publicAPI`. A map component's `publicAPI` includes the `mapComponent` instance by default.

```js
myEventHandler( { target, publicAPI } ) {
  let mapComponent = publicAPI.mapComponent;
}
```

**Comment by HodofHod** [comment]
Ah, that makes sense, thanks!. Should I change this to a documentation issue, or just close it?

**Comment by acorncom** [comment]
@HodofHod switching it to a documentation issue would seem to make sense ...
