### ISSUE TITLE
How do I load a utility library like infobox.js without triggerring 'google is not defined' error?

### ISSUE THREAD

**Issue by alexmasita** [sandydoo/ember-google-maps#44]
I have a need of using the following utility library which is actually a more customizable version of google maps infowindows: [infobox.js source](https://raw.githubusercontent.com/googlemaps/v3-utility-library/master/infobox/src/infobox.js).

I tried adding it the usual way through importing it in the `ember-cli-build` from vendor directory and then adding a new component aptly called `info-box`.  I removed the template file so it uses the `info-window` template instead and this is what I put in the javascript file:
```
import InfoBox from 'info-box';
import GoogleMapInfowindow from 'ember-google-map/components/g-map/info-window';
import {
  set
} from '@ember/object';
export default GoogleMapInfowindow.extend({
  _type: 'infoBox',
  _addComponent() {
    this._prepareContent();

    let options = this._getOptions();

    set(this, 'mapComponent', new InfoBox(options));
  }
});
```

The above way of extending and overriding the google `info-window` component worked with my previous `ember-g-map` addon because `infobox.js` is meant to be an exact copy of google infowindow except with the added features and customizability.  

On running my application after the above I understandably get the `google is not defined` error.

I know I can use your custom overlays contextual component but it lacks some features which are available in `infobox.js` which actually extends `google.maps.OverlayView` class.  Some of the features missing from your `custom overlays` are `pixelOffset` and `alignBottom ` which are both options that can be passed to a new instance `infobox`.  Both of these allow me to offset/reposition the `infobox` popup relative to the pin point location.

My application was already using `infobox.js` extensively so it would be nice to port this somehow to the ember-google-maps contextual components.

Any advice on how to achieve this even minimally?

**Comment by acorncom** [comment]
@alexmasita with this addon, the Google Maps script isn’t loaded until you request it and then returns a promise (see https://github.com/sandydoo/ember-google-maps/blob/master/addon/services/google-maps-api.js) You’ll need to watch the service and make sure the promise has resolved before calling your custom component.

See for a few details on that.

There’s also a recent PR of mine that allows you to integrate in more thoroughly if you went to use a contextual component: https://github.com/sandydoo/ember-google-maps/pull/38

**Comment by acorncom** [comment]
Skimming the infobox source a little, it looks like you may be hitting problems on this line:

```
InfoBox.prototype = new google.maps.OverlayView();
```

as that assumes a global `google` that is already loaded. If you manually add a Google Maps script tag to your `index.html` file before your `vendor.js` is loaded do you still see the problem?

As far as the `g.outlet` goes, yes, you are able to pass down the map context to children routes, as when you load up as a contextual component inside of a `g-map` that map object is passed to you. I built it for a client and it worked quite well, but haven’t yet put it up online. Sounds like it’d help you?

What is the use case you’re trying to solve?

**Comment by alexmasita** [comment]
Dear @acorncom, thanks for your response.

I will try adding a google maps script tag in my index.html to see if the issue goes away.  But would that be the way to resolve this issue given the ember-google-maps addon already somewhat includes the google maps api albeit asynchronously?

About the outlet, it is great that it can pass the context, after all, it is an ember component :).  

For an idea of the usecase for the `g.outlet` please look at the template for the map in question:
```
{{#g-map lat=centerMap.currentLat lng=centerMap.currentLon zoom=centerMap.zoom disableDefaultUI=true onDragend=(action "onDragend") as |g|}}
      {{#if isWhereToGo}}
        {{#if originIcon}}
          {{g.marker lat=centerMap.currentLat lng=centerMap.currentLon icon=originIcon}}
          {{!--#g.infoBox lat=currentLat lng=currentLon}}
            <h4 class="location-title">{{currentTitle}}
              <i class="material-icons">&#xE315;</i>
            </h4>
          {{/g.infoBox--}}
        {{/if}}
        {{#g.overlay lat=centerMap.currentLat lng=centerMap.currentLon}}
          <div class="infoBox">
            <h4 class="location-title">{{currentTitle}}
              <i class="material-icons">&#xE315;</i>
            </h4>
          </div>
        {{/g.overlay}}
      {{else if isRouteSelector}}
        {{#if isMapped}}
          {{g.marker lat=rider.originLat lng=rider.originLon icon=originIcon}}
          {{#g.overlay lat=rider.originLat lng=rider.originLon}}
            <div class="infoBox">
              <h4 class="location-title">{{rider.originFusedAddressName}}
                <i class="material-icons">&#xE315;</i>
              </h4>
            </div>
          {{/g.overlay}}
          {{g.marker lat=rider.destinationLat lng=rider.destinationLon icon=destinationIcon}}
          {{#g.overlay lat=rider.destinationLat lng=rider.destinationLon}}
            <div class="infoBox">
              <h4 class="location-title">{{rider.destinationFusedAddressName}}
                <i class="material-icons">&#xE315;</i>
              </h4>
            </div>
          {{/g.overlay}}
          {{#g.directions origin=origin destination=destination travelMode="DRIVING" onDirectionsChanged=(action "onDirectionsChanged") as |d|}}
            {{d.route polylineOptions=(hash strokeColor="green") preserveViewport=true markerOptions=(hash visible=false)}}
          {{/g.directions}}
        {{else if rider.originLat}}

          {{g.marker lat=rider.originLat lng=rider.originLon icon=originIcon}}
          {{#g.overlay lat=rider.originLat lng=rider.originLon}}
            <div class="infoBox">
              <h4 class="location-title">From: {{rider.originFusedAddressName}}
                <i class="material-icons">&#xE315;</i>
              </h4>
            </div>
          {{/g.overlay}}
        {{else if rider.destinationLat}}
          {{g.marker lat=rider.destinationLat lng=rider.destinationLon icon=destinationIcon}}
          {{#g.overlay lat=rider.destinationLat lng=rider.destinationLon}}
            <div class="infoBox">
              <h4 class="location-title">To:
                {{rider.destinationFusedAddressName}}
                <i class="material-icons">&#xE315;</i>
              </h4>
            </div>
          {{/g.overlay}}
        {{else}}
          {{#if rider.lat}}
            {{g.marker lat=rider.lat lng=rider.lon icon=originIcon}}
            {{#g.overlay lat=rider.lat lng=rider.lon}}
              <div class="infoBox">
                <h4 class="location-title">You
                  <i class="material-icons">&#xE315;</i>
                </h4>
              </div>
            {{/g.overlay}}
          {{/if}}
        {{/if}}
      {{/if}}
    {{/g-map}}
```
You will notice there are conditional if blocks which are activated when certain routes are visited.  Can you see how this can make this template too verbose if a few more conditional blocks for new routes are added?  I feel It would be nicer instead to be able to put the code snippets above within the various route templates which would get injected on the above template when the route is visited.

Let me know your thoughts and thank you.

**Comment by sandydoo** [comment]
The only safe way of handling this is to delay this line as pointed out by David.
```js
InfoBox.prototype = new google.maps.OverlayView();
```
How you want to do that is up to you, but the best approach would be to modify the utility library. Wrap it in a function or something and call it once `google` is loaded.

For example, you can wait for `google.maps` by using the promise on the `googleMapsApi` service, as pointed out by David.
```js
import Component from '@ember/component';
import { inject as service } from '@ember/service';

export default Component.extend({
  googleMapsApi: service(),
  
  init() {
    this._super(...arguments);

    this.get('googleMapsApi.google').then((google) => {
      // Google Maps is loaded and initialized. Safe to use!
    });
  }
})
```

You could also browse the component implementations, like [info window](https://github.com/sandydoo/ember-google-maps/blob/master/addon/components/g-map/info-window.js), and make it work for your case. Look at  the `_addComponent` function there. It will be called only once google is done loading.

https://github.com/sandydoo/ember-google-maps/blob/d397f6546c851f9f451b21c6ea9ee97c76fca179/addon/components/g-map/info-window.js#L42-L48

**Comment by acorncom** [comment]
@alexmasita I just released https://github.com/acorncom/ember-google-maps-outlet which packages up what I'd discussed above. The dummy app is setup to work with a really simple example. We should probably move discussions over there though so we don't clog this issue tracker ... 😉

**Comment by alexmasita** [comment]
@acorncom.  That is great!  Will check it out and revert.  Sweet.
