### ISSUE TITLE
Polyline deprecation warning because of _watchedOptions

### ISSUE THREAD

**Issue by michelvermeer** [sandydoo/ember-google-maps#45]
### Describe the bug
Using polylines in Ember 3.6 creates a deprecation warning when destroying the component. This is caused by prototype function listener specified in g-map/polyline.js R15: _watchedOptions.

### To Reproduce
1. Add a polyline
{{g.polyline path=map.route geodesic=true strokeColor="#58a5d3" strokeOpacity=0.7 strokeWeight=2}}

2. Navigate to a different page of remove the block containing the polyline.

3. Console:
DEPRECATION: You attempted to remove a function listener which did not exist on the instance, which means it was an inherited prototype listener, or you attempted to remove it before it was added. Prototype function listeners have been deprecated, and attempting to remove a non-existent function listener this will error in the future. [deprecation id: events.inherited-function-listeners] See https://emberjs.com/deprecations/v3.x#toc_events-inherited-function-listeners for more details.

**Comment by acorncom** [comment]
Looks like it’s the add/remove observer calls at the top of https://github.com/sandydoo/ember-google-maps/blob/master/addon/mixins/process-options.js

**Comment by alexmasita** [comment]
I am hitting the same issue when navigation from a route that has the " {{g.directions}}" component.  Have tracked the issue to  https://github.com/sandydoo/ember-google-maps/blob/master/addon/mixins/process-options.js.  Any hope of a resolution soon?
