### ISSUE TITLE
ember-google-maps update 

### ISSUE THREAD

**Issue by david-system** [sandydoo/ember-google-maps#47]
Hi Dear

I am David, hope You can help me. I have a "Google Maps JavaScript API warning: RetiredVersion" warning and as said in documentation I changed version: '3.34' to version: '3.35', and update version "ember-google-maps": "^2.1.0". Now I have same warning too, besides that map not open first time before reinit.

Thanks for understanding.

**Comment by sandydoo** [comment]
@david-system, there are two likely alternatives: either something is wrong with your configuration or you need to restart your ember server after changing the version number.

If you take a look at the [version documentation](https://developers.google.com/maps/documentation/javascript/versions#choosing-a-version-number), `3.34` is a currently supported version. It's likely that you're still loading a version lower than that, e.g. `3.31`.

You can always check the currently loaded version using the console and the network tab.

![g-map-2](https://user-images.githubusercontent.com/7572407/51177079-b413bc80-18cf-11e9-8dbb-d02ebe184159.jpg)

<img width="696" alt="g-version" src="https://user-images.githubusercontent.com/7572407/51176807-eec92500-18ce-11e9-8d51-765b4baf8344.png">

**Comment by david-system** [comment]
Thanks for answer @sandydoo  ))
I'll try to restart my ember server.

Thanks for everything ))
![google-map](https://user-images.githubusercontent.com/18840163/51177950-98fa7a00-18da-11e9-9859-759374f1ad9a.png)

**Comment by sandydoo** [comment]
No problem. You can actually see that the source of the warning in your screenshot is `@ js?v=3.31...`. Unfortunately,  instead of providing that old version, Google just forcibly returned the latest version instead.
