### ISSUE TITLE
Assertion Failed: You cannot create a component from undefined using the {{component}} helper

### ISSUE THREAD

**Issue by Dominicbarretto** [sandydoo/ember-google-maps#48]
so i m using ember version 3.0.0, so i have used this addon, the markers, overlay etc works fine,
but only issue what i m facing now is when i using this code

{{#g-map lat="51.507568" lng="-0.127762"
  zoom=12
  styles=primaryMapStyle as |g|}}

  {{!-- A manually positioned info window with basic text --}}
  {{g.infoWindow lat=london.lat lng=london.lng
    isOpen=mapTooltipOpen
    content="Simple text tooltip"}}

  {{!--
    An info window attached to a marker component.
    Notice how it is yielded by the marker itself.
    This info window displays the template defined in the block --}}
  {{#g.marker lat=london.lat lng=london.lng
    onClick=(action (toggle "markerTooltipOpen" this)) as |m|}}
    {{#m.infoWindow isOpen=markerTooltipOpen as |i|}}
      <div class="text-center">
        <img src="/images/doge-dbce44312027ca7f16631937e62ff5e9.jpg" alt="Such doge!" width=200>
        <div>Custom <i>HTML</i> content in infoWindow!</div>
      </div>
    {{/m.infoWindow}}
  {{/g.marker}}
{{/g-map}}

this is the exact copy from the documentation, when i use  i get this error
"Error: Assertion Failed: You cannot create a component from undefined using the {{component}} helper↵   

this is from my ember-cli-build.js
'ember-google-maps': {
      only: ['marker', 'info-window', 'overlay']
      // exclude: ['overlay']
    },

and this is from my config/enviroment.js
ENV['ember-google-maps'] = {
    key: 'fdsfdsfsdfdsfdsfsdfsdf', // Using .env files in this example
    language: 'en',
    region: 'GB',
    protocol: 'https',
    version: '3.35',
    libraries: ['geometry', 'places'], // Optional libraries
    // client: undefined,
    // channel: undefined,
    // baseUrl: '//maps.googleapis.com/maps/api/js'
  }

can u tell me what i am doing wrong or what am i missing

**Comment by acorncom** [comment]
If you comment out your ember-cli-build lines does it work for you? I’ve found that a little tricky to get right sometimes...

**Comment by Dominicbarretto** [comment]
yes it works once i comment the ember-cli-build lines, but that means all unwanted componets will also be loaded by the addon

**Comment by acorncom** [comment]
In a client app on my end, I ended up needing these at one point:

```
'control', 'infoWindow', 'info-window', 'marker', 'map-component', 'overlay'
```

I'm not sure I **actually** need `infoWindow` but `map-component` looks like it'd be worth trying. Does that fix it for you?

**Comment by sandydoo** [comment]
I'll have a look at this. I think there's been some sort of mixup with format of the component names (dashed vs camelCase). It's entirely possible that it doesn't work at all. I would suggest removing the whole treeshaking bit from your ember-cli-build file.

> but that means all unwanted components will also be loaded by the addon

Yes, but it's not worth the effort in this case if it doesn't work well. 

> I’ve found that a little tricky to get right sometimes...

Yeah, in hindsight the whole treeshaking implementation is far from great. It might be best to get rid of it entirely.

I'll close this and open another issue as a reminder to deal with the build system. Thanks for reporting!
