### ISSUE TITLE
Improve treeshaking

### ISSUE THREAD

**Issue by sandydoo** [sandydoo/ember-google-maps#49]
* [x] Fix keys. 
* [x] Implement tests.
* [x] Warn when configured incorrectly. We should strive to avoid issues like #59.

**Comment by AndreJoaquim** [comment]
My two cents: it's an awesome feature to keep! 😄

**Comment by acorncom** [comment]
I've been a fan myself 😉

**Comment by AndreJoaquim** [comment]
@sandydoo Was this issue fixed per https://github.com/sandydoo/ember-google-maps/commit/025e519c116846b8b3301bd6da9e50e33f9657f6?

**Comment by sandydoo** [comment]
@AndreJoaquim, yes. I won't be publicizing the feature in the docs until I add tests and some sort of method of warning people when they try using a "treeshaken" component.
