### ISSUE TITLE
Support optional automatic map bounds management

### ISSUE THREAD

**Issue by steveszc** [sandydoo/ember-google-maps#5]
It would be great if `ember-google-maps` offered a utility for automatically managing the zoom and center of the map based on the components placed the map.

`ember-g-map` offers this feature with it's `markersFitMode` property on the `g-map` component. The markersFitMode parameter can be used instead of, or as an override to, the explicit lat/lng/zoom properties. With `markersFitMode='init'` ember-g-map will automatically set the map bounds to contain all of the markers shown on the map, and when `markersFitMode='live'` it will also update the map bounds as markers are added or removed from the map. 

I would suggest a few improvements over the `ember-g-maps` implementation:

1. Automatic bounds management should be based on markers, circles, infowindows, overlays and polylines (not just markers). This should also be configurable, for example if you need your map to auto-bound to circles but not markers. Additionally, we could add an API to make this opt-in on the component level so that any individual map components can be flagged for inclusion in the map's bounds.

2. The `ember-g-maps` implementation doesn't keep track of whether a user has manually altered the zoom or pan of the map, so any change to the markers will reset the map pan/zoom. This can be jarring in situations where a user has zoomed or panned the map, only to have their work blown away by a data change they may not have triggered. There should be a configuration to allow the map to disable the auto-bounding behavior if a user has manually adjusted the map's pan or zoom. Additionally, a method could be exposed allowing `map.fitBounds` to be manually triggered.

3. An option should be provided to chose whether fitBounds or panToBounds is used under the hood when the map bounds change as a result of auto bounds management.

4. The overall API for enabling and configuring this behavior needs some thought. Should it be another contextual component (`{{g.bounds-manager mode='init' pan=true}}`) or should this be a parameter(s) on the `{{g-map}}` itself?

5. As part of this feature work, it may be worth considering adding the ability to pass the `{{g-map}}` a bounds parameter instead of lat/lng/zoom.

If there is agreement that this is a desirable feature to add to the addon, and an API is agreed on, I would be happy to work on implementation. 

**Alternatives**
Most of these features could probably be implemented outside of the `ember-google-maps`, either as a "plugin" addon or a custom in-app component designed to be used inside a `{{#g-map}}` block. Some of the features I've suggested can't be done without changing `ember-google-maps`.

**Comment by sandydoo** [comment]
`4` I think the `g-map` component is out of the question for this. Its job is to create the map, yield some components and expose a publicAPI. Managing bounds is related to map logic and that's up to the user to figure out and implement according to their own needs. `1, 3` There's just no way we can handle every single bounds-related use case in a way that's worth the effort. It's often more cost/time-effective to handle these things on a case-by-case basic within the consuming app.

That being said, I'm not saying someone won't find something like this useful.

You could easily implement this today in your own app. `onLoad` and `onComponentLoad` both return a hash with the map instance and a `publicAPI` object with all the components. Loop over whatever markers you want or watch the arrays for changes. Get the marker component bounds, extend them and use the map instance to pan or fit to the bounds. You could even add a listener to the map and listen for drag events and what not to enable or disable your bound fitting. If you've got many maps, make it reusable.

It's a bit harder to do exactly what you're proposing today, but I'm working a plugin solution that will make it easier. You'll have access to the map instance, the internal API, the contextual components and all the displayed map components instances. You'll be able to implement this as a component in your app or as a component in an external addon.

Regarding `5`, I'm not sure. It's not something supported by Google Maps. You can use the `onLoad` hook to fetch the map instance and set the bounds that way.

**Comment by sandydoo** [comment]
I've merged #17 which lets you create your own addons. It needs some documentation, but should cover this use-case.
