### ISSUE TITLE
Memory leak introduced by Google Maps

### ISSUE THREAD

**Issue by olegstepura** [sandydoo/ember-google-maps#51]
Hi! This map addons looks amazing and I cannot wait to start using it instead of `ember-g-map`. But some issue that we faced seem to be an issue with this addon as well and I wonder if you are aware of it and maybe have plans on fixing it.

I'm talking about memory leaks which Google Maps produce because there is no proper cleaning after we remove a map from page. 
Here is an issue reported to google years ago https://issuetracker.google.com/issues/35821412
And it has status `Won't fix`. The only answer on how to solve that in that thread is recommendation to reuse (map canvas?) somehow.

I tried to check examples on your website which seem to be fully built in Ember with the use of this amazing addon. If I navigate between Directions and Controls examples multiple times I can see that memory is leaking.

I wonder how that would be if we would use multiple long-distance directions. This is what seem to make maps to leak heavily in our case because of huge arrays of coordinates from DirectionService.

So the questions are:

1. Are you aware of this issue?
2. Did you already try to reuse map canvas? Maybe you did and faced some unsolvable issues...
3. Do you see how this can be done? Workarounds? A plugin to this addon? Anything?

**Comment by sandydoo** [comment]
Hi @olegstepura,

1. I wasn't aware of this 🤦‍♂️ . I can see a bunch of detached nodes and event listeners that don't get removed. You'd have to load a lot of maps to see a significant impact on the docs website, but I assume this gets worse if you try displaying tons of data. Would you mind sharing how much memory is consumed in your routing scenario? What's the worse case scenario here?

2. No, I've never tried this. 

3. I suppose it could be done. With some reorganization, the `g-map` component *could* be made to either use a provided map instance and canvas *or* create and cache a new instance/canvas pair. Perhaps these instances should be uniquely named, I don't know. 

In any case, this is assuming that "reuse" is an effective approach. What happens to the markers, routes, etc? Does google maps clean up after these elements if we use `.setMap(null)`? Or do we have to reuse these elements as well?

**Comment by olegstepura** [comment]
After I posted original question we started working on a solution to fix this. And we already have a solution we use with `ember-g-map` (we did not migrate to `ember-google-maps`)
1. We have a service for maps. In service we have maps pool (an array). When creating a map we either take one from pool if pool is not empty or create a new one and return it. When component with map is destroyed - it calls a method of service to release the map providing map instance as an argument (only this time map is placed to maps pool).
2. when creating map instance we do `const canvas = document.createElement('div')` and `const fragment = document.createDocumentFragment(); fragment.appendChild(canvas);` to have map canvas contained in a fragment.
3. map component uses that service. it asks for map and places fragment with canvas to some placeholder.
4. When releasing map we detach map canvas element from DOM (detached element is not a fragment then, just dom node)

That's it. We reuse the map elements and reset map options when map is reused. One thing to note is that map needs to be rezoomed after resuse - but this you find out while testing.

This helps to solve the issue with map leaking itself.

We also had an issue with polylines leaking with `ember-g-map`. And this was the heaviest leak. Regarding how much this affected us - we had memory issues with complex routes where each page load we lost about 100Mb of RAM. Meaning 10 times you go back and forth and Chrome tab is using more than 1Gig. We solved this by managing polylines manually without `ember-g-map` components. 

Good way to test if polylines solution leaks - create a driving route from NY to LA. Even better - create another one to drive back. Driving path is pretty long then and uses a lot of RAM.

**Comment by sandydoo** [comment]
Thanks, @olegstepura.

I'll give this some thought. In the meantime, I'll keep this open for reference and in case others want to chime in.

**Comment by alexmasita** [comment]
Fantastic addon, this.  And it would be great if it could solve this behind the scenes.  For long lived apps, the solution to the leaking is a must.

**Comment by ianpetzer** [comment]
Just wondering if the code that implements the solution outlined above is available anywhere in a public repo or fork?

**Comment by olegstepura** [comment]
Hi, @ianpetzer! No, sorry, only in private repo that cannot be shared. The idea was to have a service that manages the maps and reuses instances.

**Comment by ianpetzer** [comment]
ok.. Well many thanks for the notes on how it can work.
