### ISSUE TITLE
Overlay documentation suggestion (innerContainerStyle)

### ISSUE THREAD

**Issue by nselikoff** [sandydoo/ember-google-maps#54]
Thanks so much for this addon - I'm in the process of migrating from `ember-g-map` and it's been relatively painless.

For the overlay component, the `innerContainerStyle` is set up nicely for tooltip type content whose anchor is at the bottom middle of the content. However, if you have content that is meant to be centered on the lat/lng (e.g. a user location circle), you need to override `innerContainerStyle` to `htmlSafe('transform: translateX(-50%) translateY(-50%);')`. I would suggest including a note to this end in the docs.

I'm not sure if your docs site is a separate and available repo or included in the main `ember-google-maps` repo; if so, please feel free to point me to it and I'll submit a PR.

**Comment by sandydoo** [comment]
Thanks, @nselikoff. I've updated the docs 👍
