### ISSUE TITLE
onComponentsLoad is invoked twice

### ISSUE THREAD

**Issue by mistahenry** [sandydoo/ember-google-maps#56]
Is it intentional that `onComponentsLoad` is invoked two times? This was not documented nor expected and feels like a bug to me. In `_initMap` in `g-map.js`, the `_waitForComponents` function invokes `onComponentsLoad` and the `afterRender` function which invokes `_waitForComponents` invokes it as well on resolution of the `_waitForComponents` promise:

```javascript
scheduleOnce('afterRender', this, () => {
  if (this.isDestroying || this.isDestroyed) { return; }

  this._waitForComponents()
    .then(() => {
      this._componentsInitialized = true;
      tryInvoke(this, 'onComponentsLoad', [this.publicAPI]);
    });
});
```

```javascript
  _waitForComponents() {
    let componentsAreInitialized =
      Object.keys(this.components)
        .map((name) => this.components[name])
        .reduce((array, componentGroup) => array.concat(componentGroup), [])
        .map((components) => get(components, 'isInitialized.promise'));

    return all(componentsAreInitialized)
      .then(() => {
        this._componentsInitialized = true;
        tryInvoke(this, 'onComponentsLoad', [this.publicAPI]);
      });
  },
```
This initially lead to bugs for me and I'm having to ensure I call my handler only once

**Comment by sandydoo** [comment]
Thanks for taking the time to write this up, @mistahenry.

Not at all intentional. I believe I've already fixed this in my local branch, but I guess it didn't click in my head that it needed more urgent patching. I'll get it done.
