### ISSUE TITLE
infowindows not opening

### ISSUE THREAD

**Issue by fran-worley** [sandydoo/ember-google-maps#59]
### Describe the bug
Firstly, thank you so much for building such a lovely api wrapper for google maps, the move from `ember-cli-g-maps` has removed so much code!!

Apologies if I'm missing something basic but I can't seem to get my infowindows to open. I know that the open attribute is being set correctly but for some reason the windows themselves aren't showing.

### To Reproduce
```javascript
// controller.js
actions: {
  onMapLoad(publicApi) {
    set(this, 'gmapApi', publicApi);
    // this is then used to manually set the bounds of the map once the site 
    // markers are loaded which is why I don't set a lat and lng for the map initially
  }
}
```

```hbs
// template.hbs
  {{#g-map 
    disableDefaultUI=true 
    zoomControl=true
    onLoad=(action "onMapLoaded") 
  as |g|}}    
    {{#each sites as |site|}}
      {{#g.marker 
        lat=site.address.latitude
        lng=site.address.longitude
        onClick=(action (toggle "mapInfoWindowOpen" site))
      as |marker|}}
        {{marker.infoWindow isOpen=site.mapInfoWindowOpen content="test"}}
      {{/g.marker}}
    {{/each}}
  {{/g-map}}
```

### Attempted solutions
I've tried following you instructions [here](https://github.com/sandydoo/ember-google-maps/issues/11) for creating one infowindow and changing the target but I get the same result.

--------------------------------------------------------------------------------

### Addon configuration and device details

- ember version: 3.9.0

**Addon configuration**:

 - Addon version: 2.1.1
 
 - Addon config from `environment.js` (**do not** post your API key): 
```javascript
  ENV['ember-google-maps'] = {
    key: process.env.GOOGLE_MAPS_API_KEY, // Using .env files in this example
    language: 'en',
    region: 'GB',
    protocol: 'https',
    version: '3.35',
    libraries: ['drawing'], // Optional libraries
    // client: undefined,
    // channel: undefined,
    // baseUrl: '//maps.googleapis.com/maps/api/js'
  };
```
  - Addon config from `ember-cli-build.js`: 
```javascript
    'ember-google-maps': {
      only: ['marker', 'info-window']
    }
```

 - Google Maps version: 3.35
 
**Desktop:**
 - OS: osx 10.14.3
 
 - Browser: chrome
 
 - Version: 73.0.3683.86

**Comment by sandydoo** [comment]
Hey, @fran-worley.
It's probably the component whitelist `only: ['maker', 'info-window']`. This feature broke at some point (#49) , never had tests, and can be quite fiddly to configure.
I'll cut that bit out from the docs until it's fixed. Sorry for the trouble! I realize how frustrating these issues can be 😞

**Comment by fran-worley** [comment]
@sandydoo as simple as that!! removed the build config and my info windows started to work!
