### ISSUE TITLE
How to call the g.canvas component and be able to put other components inside it as well as outside?

### ISSUE THREAD

**Issue by alexmasita** [sandydoo/ember-google-maps#62]
Have seen the example of being able to call the canvas component to be able to place other components/mark up outside of the map canvas, but what if you also want other components within the canvas at the same time?

**Comment by sandydoo** [comment]
Hey @alexmasita,
Do you have an example you could share that uses this? I added a yield in the latest version, but would like to have an idea of what this would be used for. Note that you'd need to set the [noClear](https://developers.google.com/maps/documentation/javascript/reference/map#MapOptions.noClear) option to `true` as well.
