### ISSUE TITLE
performance consequences of component per google-maps construct

### ISSUE THREAD

**Issue by mistahenry** [sandydoo/ember-google-maps#63]
First off, I want to say that this library is a really elegant way to interface with google maps. I love the declarative style. But I'm experiencing serious performance degradation when trying to scale to a growing number of markers which has caused me to temporarily role my own solution. I'd like to discuss what you would be open to in this library when scale becomes an issue (or how we can improve ember-google-maps to better support lots of markers).

In my own application, I've gone from needing to show ~50-100 pins to 750 pins - 1000 pins overnight. When entering my route with the map, the load time takes anywhere from 3-6 seconds on my macbook pro in chrome and as much as 20 seconds on some older android devices. I've profiled the slow loading and it's not google, it's the amount of time spent in the rendering engine for ember that's bottlenecking. Furthermore, my own handrolled solution renders 1k instantly. 

Consider this markup:

```hbs
{{#g-map as |map|}}
    {{#each locations as |location|}}
        {{#map.marker lat=location.latitude lng=location.longitude onClick=(action "openLocationPopup" location) as |marker|}}
            {{#marker.infoWindow isOpen=(eq activeLocation location) as |i|}}
                {{!-- more components here --}}
            {{/marker.infoWindow}}
        {{/map.marker}}
    {{/each}}
{{/g-map}}
```

All of that is evaluated at render time despite no marker.infoWindow being shown at render time. There is a non-negligible overhead to creating a component per marker.  Even if I clustered the markers via the standard google clustering lib, to leverage such a component based approach as done here means I'm still stuck in the render bottleneck of glimmer trying to work through a lot of components that arent even rendering anything yet (or ever).

What i've implemented in my own project is a markers-layer that receives all locations for me to render with an inner component for the marker window that's used for a yielded current location.

**Comment by sandydoo** [comment]
I won't deny that there's nothing to be optimized here, but there are things that are out of my scope. Yes, there is overhead with the component system. Yes, we don't need even half of what components offer. Yes, Ember and Google Maps run separate rendering loops with their own schedulers that fight each other. We can't mess with this part of the equation. Perhaps Ember Octane and its simpler components will reduce some of the overhead, perhaps it won't. Maybe custom components are the answer if and when they become available.
Also, I'd like to mention that 1000 markers is not a performance target I'm looking for for this addon. 100-200 is a more realistic target at the moment.

> All of that is evaluated at render time despite no marker.infoWindow being shown at render time.

Yes, there is some expensive prep done to avoid rendering lag and weird layout issues when opening an info window. There is totally room for improvement here. You could also try reusing one info window, as suggested by google themselves.

> What i've implemented in my own project is a markers-layer that receives all locations for me to render with an inner component for the marker window that's used for a yielded current location.

And this is totally fine. Write a custom component or copy paste what you need. Hopefully, we'll get to a point where you won't need it anymore.

I would advise not dwelling too much over this. We'll see what Ember Octane brings and move on from there. If you do have performance comparisons to post, anything specific you've found, etc, please do.

**Comment by acorncom** [comment]
@mistahenry given that the 1000 marker scenario probably isn't the focus here, maybe you could develop an ember-maps addon that allows the same sort of declarative api for folks who have performance considerations?

`ember-maps-performant-markers` or something like that?

**Comment by mistahenry** [comment]
> I would advise not dwelling too much over this.

Taking 12-15 seconds to transition into my route that shows my map on a Google Pixel 3 more or less forced me to dwell on it ;)

> Also, I'd like to mention that 1000 markers is not a performance target I'm looking for for this addon. 100-200 is a more realistic target at the moment.

This might be helpful disclaimer in the README. I assumed that I could just enhance this addon to cluster when I had lots of pins, but the current architecture makes that a nonstarter.

**Comment by mistahenry** [comment]
@acorncom that's the plan with clustering built in.

**Comment by sandydoo** [comment]
@mistahenry, in case you're interested, I've published a test app that I've been using to measure the performance of the markers here. Results will vary based on hardware and dev/production build.

[ember-google-maps-performance-test](https://github.com/sandydoo/ember-google-maps-performance-test)

### Some results

> Perhaps Ember Octane and its simpler components will reduce some of the overhead

* The simpler Glimmer components drastically cut down setup time. There is still substantial overhead.

* Custom components save comparatively little over Glimmer components, since there isn't much else we can cut out from the rendering loop. 😞 Maybe someone knows a way we can create simple functional components? i.e. no rendering, just a method call?

* Helper components are *slightly* faster that Glimmer components, but are a no-go for some of the more complex components.

* Drawing markers in js is, of course, the best option. However, 1000 markers are still a non-trivial amount.
