### ISSUE TITLE
onDirectionsChanged causes a google map error

### ISSUE THREAD

**Issue by IAmJulianAcosta** [sandydoo/ember-google-maps#64]
### Complete this checklist before opening an issue

*Please read the documentation before opening an issue*. Once you understand how this addon works, you will find that most problems can be solved by consulting the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've read the relevant documentation for this addon on [ember-google-maps.sandydoo.me](https://ember-google-maps.sandydoo.me/docs/getting-started).

* [x] I understand how to set options on the components in this addon. Options are not hardcoded. Arguments passed to a component are used to set the options on the map component.

* [x] I've searched the relevant section of the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've [searched the closed issues](https://github.com/sandydoo/ember-google-maps/issues?q=is%3Aissue+is%3Aclosed) for similar problems.

--------------------------------------------------------------------------------

### Describe the bug
`onDirectionsChanged` causes a google map error: `Cannot read property 'addEventListener' of undefined`

### To Reproduce
Steps to reproduce the behaviour, or a link to a reproduction repo or twiddle.

```
{{#g-map
    lat="51.508530"
    lng="-0.076132"
    zoom=12
    onLoad=(action "mapLoaded")
  as |g|}}
    {{#g.directions
      origin="Covent Garden"
      destination="Clerkenwell"
      travelMode="WALKING"
      onDirectionsChange=(action "onDirectionsChange")
    as |d|}}
    {{/g.directions}}
  {{/g-map}}
```

### Expected behaviour
Action executes

### Attempted solutions
Investigated the error, looks like when trying to add eventListener in `register-events` mixin, `_eventTarget` is undefined for that component

--------------------------------------------------------------------------------

### Addon configuration and device details

**Addon configuration**:

 - 2.1.1
 - Addon config from `environment.js` (**do not** post your API key): 
```
{
    language: 'en',
    region: 'US',
    protocol: 'https',
    version: 'quarterly',
    libraries: ['geometry', 'places'], 
}
```
 
 - Google Maps version: 3.36.12a
 
**Desktop:**
Chrome 75 in windows

**Comment by sandydoo** [comment]
Hi @IAmJulianAcosta,
The event in your code snippet should be called `onDirectionsChanged`, not `onDirectionsChange`. That's likely to be the problem here.

`onDirectionsChange` shouldn't throw errors though. I'll look into it.

**Comment by IAmJulianAcosta** [comment]
you are right, `onDirectionsChanged` works, thank you
