### ISSUE TITLE
AngleBrackets canvas class problems in ember-google-maps 2.2.1

### ISSUE THREAD

**Issue by Windvis** [sandydoo/ember-google-maps#67]
We're defining maps using AngleBracket notation. Since the 2.2.1 release classes set through the `class` attribute aren't passed to the canvas div anymore:
```hbs
<GMap
  @lat={{config.map.center.lat}}
  @lng={{config.map.center.lng}}
  @zoom={{config.map.zoom}}
  as |g|
>
  <g.canvas class="h-full w-full" />
</GMap>
```

Passing them using `@classNames="h-full w-full"` works though. 

I know this functionality wasn't documented before, but it would be nice if attributes could be splat on the div somehow.

**Comment by sandydoo** [comment]
Thanks, @Windvis. Looks like I got bit by Ember's `class` vs. `classNames` shenanigans. I'll make sure `class` still works. 

I'm working towards a full Octane release. That will, of course, splat all of the attributes. 😄
