### ISSUE TITLE
Example error for controls in docs. 

### ISSUE THREAD

**Issue by iwilliams** [sandydoo/ember-google-maps#7]
At https://ember-google-maps.sandydoo.me/docs/controls the `g.control` example has the position property set to `position="TOP CENTER"` when it should be `position="TOP_CENTER"`. I didn't see a gh-pages branch or anything so reporting this here. Thanks!

**Comment by sandydoo** [comment]
Thanks, @iwilliams. Fixed 5e18ce0cb3a90c6e543ee0cc67281a699370f869
