### ISSUE TITLE
Make it possible to adjust the zIndex of map components

### ISSUE THREAD

**Issue by Windvis** [sandydoo/ember-google-maps#70]
It would be nice if map components had a zIndex attribute to make it possible to influence the display order. In our app we have a focus state for certain components, but they aren't always displayed on top.

Any suggestions on how you would implement something like that?

**Comment by sandydoo** [comment]
Hi @Windvis!
When you say "map components" are you talking about overlays or other components?

**Comment by Windvis** [comment]
Also other components. We also render multiple directions and polylines components, which also could use some sort of zIndex tweaking in our app.

**Comment by sandydoo** [comment]
Doesn't the [zIndex](https://developers.google.com/maps/documentation/javascript/reference/polygon#PolylineOptions.zIndex) option do what you are describing?

**Comment by Windvis** [comment]
🙈 Looks like it does, yea. I'm not super familiar with the Maps API. Must have missed it the last time I checked the docs 😄.

I mainly opened this issue because of your comment [here](https://github.com/sandydoo/ember-google-maps/pull/55#issuecomment-489862607) which mentioned adding a zIndex option.
