### ISSUE TITLE
Is there a way to create boundaries ?

### ISSUE THREAD

**Issue by claeusdev** [sandydoo/ember-google-maps#71]
So i am working with some large data set which has boundary data in the component. I would like to create a boundary around this area? Is that what a polyline does?

**Comment by acorncom** [comment]
@claeusdev I've used a polyline as a boundary with good success 👍

**Comment by claeusdev** [comment]
@acorncom I used it works okay but some point in my data doesn't connect... Just wanted to know if that happens... But thanks I managed to make it work... I will try and send a PR for the docs some part I think will be helpful to users.
