### ISSUE TITLE
Missmatch in documentation related to compatibility

### ISSUE THREAD

**Issue by sredxny** [sandydoo/ember-google-maps#72]
Hi, I am starting to use this library, however there's a mismatch in the documentation that make some noise. It's about the compatibility as I explain next:

- In [ember-google-maps.sandydoo.me](https://ember-google-maps.sandydoo.me/docs/getting-started) I don't see any section about compatility

- In [the readme in github](https://github.com/sandydoo/ember-google-maps) the compatibility is for Ember.js v2.18 or above

- In [Emberobserver.com](https://www.emberobserver.com/addons/ember-google-maps) the comatibility ask for Ember.js v3.4 or above

So, which one is correct?

**Comment by acorncom** [comment]
@sredxny given https://github.com/sandydoo/ember-google-maps/commit/cc46b650528a1318e7a8db891b3913805c96e757 seems safe to assume 2.18+

**Comment by sandydoo** [comment]
> @sredxny given cc46b65 seems safe to assume 2.18+

Correct. It'll all sync in the next release.
