### ISSUE TITLE
`didUpdateAttrs` causing unnecessary rerenders

### ISSUE THREAD

**Issue by enspandi** [sandydoo/ember-google-maps#73]
Regarding https://github.com/emberjs/ember.js/issues/17397

> didUpdateAttrs is called if either of the following circumstances:
> * When passed in arguments have changed
> * Any other time 

----

> * Any other time

... applies to a scenario we currently have.

We experience issues where the `didUpdateAttrs` hook in `g-map` is called very often, even though no params have been changed, but according to the linked issue this is expected behavior. The side effect we experience is that event handlers, like `onZoomchanged` are called very often, causing itself a change of the params and so on...

Would it be a good idea to check for a change in the params, before continuing to update the Google Map?

btw. great work - love the addon :rocket: !

**Comment by sandydoo** [comment]
Hi @enspandi!
This sounds horrible. Would you be able to provide a minimal working example of this? I'm specifically interested in two things:
* What are these "any other" cases? Have you traced what exactly is triggering the updates?
* What is your event handler setup like? What does `onZoomchanged` do? Is it updating some value that is then passed as a parameter to a map component?

Also, what version of Ember are you running?
I would appreciate as much detail as you can provide.

**Comment by sandydoo** [comment]
Closing this. I'm converting the addon to Octane and there will be a more nuanced check of the arguments when updating components 👍
