### ISSUE TITLE
InfoWindow not showing

### ISSUE THREAD

**Issue by LucySuddenly** [sandydoo/ember-google-maps#83]
I'm having an infoWindow issue: the isOpen option doesn't seem to be working. I've verified that the toggle action is properly setting true false, but I can't get the infoWindow to respond

```
{{#g-map lat="39.0986106" lng="-98.6166598" zoom=4 as |g|}}
    {{#each this.model as |provider|}}
      {{#g.marker lat=provider.latlon.[0] lng=provider.latlon.[1] onClick=(action "toggle") as |m|}}
        {{#m.infoWindow isOpen=provider.markerOpen }}
          {{provider.name}}
        {{/m.infoWindow}}
      {{/g.marker}}
    {{/each}}
  {{/g-map}}

**Comment by sandydoo** [comment]
Thanks, @LucySuddenly. Everything looks correct on your end, but you may have stumbled on a bug in the info window implementation. Is your `provider.markerOpen` set to `true` by default?

P.S I had no idea `provider.latlon.[0]` was possible! :astonished:

**Comment by LucySuddenly** [comment]
markerOpen is set to false by default. 

Latlon is a custom property I set after geocoding an address in the model. It's a 2-element array with the values of lat() and lon() from the geocoder response. Did you mean you didn't know you could access array values in a template?

Thank you for looking into this!

**Comment by sandydoo** [comment]
I've tested the above code and everything opens as expected 🤷‍♂ 

Could you show snippets of your `model` and `toggle` action?
Have you excluded any components in your `ember-cli-build.js`? Can you get the most basic info window do show at all?


> Did you mean you didn't know you could access array values in a template?

Yeah, I had no idea that syntax was even thing.

**Comment by LucySuddenly** [comment]
I can't get the infoWindow to display at all. I haven't excluded anything in my ember-cli-build.

```
import Route from '@ember/routing/route';
import { inject as service } from '@ember/service';

const DECODE_IN_SEQUENCE = true;

export default Route.extend({
  geocoder: service(),

  async model() {
    return DECODE_IN_SEQUENCE
      ? this.sequencedModelHook(...arguments)
      : this.parrallelModelHook(...arguments);
  },

  async parrallelModelHook() {
    let json = await fetch('http://localhost:3000/providers').then(r => r.json());
    let decodes = json.map(async provider => {
      let { address1, address2, city, state } = provider;
      let geocodeAddress = [address1, address2, city, state].join(' ');
      let latlon = await this.geocoder.decode(geocodeAddress);
      let markerOpen = false
      return { ...provider, latlon, markerOpen };
    });
    return await Promise.all(decodes);
  },

  async sequencedModelHook() {
    let providers = [];
    let json = await fetch('http://localhost:3000/providers').then(r => r.json());
    for (let provider of json) {
      let { address1, address2, city, state } = provider;
      let geocodeAddress = [address1, address2, city, state].join(' ');
      let latlon = await this.geocoder.decode(geocodeAddress);
      let markerOpen = false
      providers.push({ ...provider, latlon, markerOpen });
    }
    return providers;
  }

});

```
import Controller from '@ember/controller';

export default Controller.extend({
    actions: {
        toggle: function() {
            this.toggleProperty('markerOpen')
        }
    }
});

**Comment by sandydoo** [comment]
I think I see the problem!

```js
this.toggleProperty('markerOpen');
```
In your toggle action, you are flipping the value of `this.markerOpen`, where `this` is the controller.

But in your template, you're reading the value of `markerOpen` from the `provider`.

```hbs
{{#m.infoWindow isOpen=provider.markerOpen }}
```

I assume you want to toggle the `provider` value instead.

**Comment by LucySuddenly** [comment]
Yes you're absolutely right. I'm a relatively new Ember user. Alright, so when I pass a provider into the toggle action and attempt to update the markerOpen property, I get the following error, which I can find no google results about: 

```
\index.js:172 Uncaught Error: Assertion Failed: You attempted to update [object Object].markerOpen to "true", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```

```
import Controller from '@ember/controller';

export default Controller.extend({
    actions: {
        toggle: function(provider) {
            provider.markerOpen = !provider.markerOpen
        }
    }
});
```

**Comment by sandydoo** [comment]
Yes, you can't directly change the value since you're using it in your template. Ember needs to know that you've changed something. You have several options here:

If `provider` is an EmberObject, it should have the `toggleProperty` method:

```js
toggle: function(provider) {
   provider.toggleProperty('markerOpen');
}
```

Otherwise, you would use `set`. Here's a snippet from the [Ember guide](https://guides.emberjs.com/release/object-model/classes-and-instances/):

> Always use Ember's [set()](https://api.emberjs.com/ember/3.11/classes/@ember%2Fobject/methods/set?anchor=set) method to update property values. It will propagate the value change to computed properties, observers, templates, etc. If you "just" use JavaScript's dot notation to update a property value, computed properties won't recalculate, observers won't fire and templates won't update.

```js
import { set } from '@ember/object';

// Works in EmberObjects and plain javascript objects
set(provider, 'markerOpen', !provider.markerOpen);

// If provider is an EmberObject
provider.set('markerOpen', !provider.markerOpen);
```

**Comment by LucySuddenly** [comment]
That did it! Thank you so much for helping me with an issue unrelated to your very good library!

**Comment by sandydoo** [comment]
You're very welcome!
