### ISSUE TITLE
Changelog and release consistency between Github and npm?

### ISSUE THREAD

**Issue by nselikoff** [sandydoo/ember-google-maps#85]
Thanks for this addon, it has been great for our needs! I'm upgrading packages and noticing that yarn is suggesting I update to `3.0.0-beta.1`. But the latest I see in Github releases is `2.2.0`. Also, is there a changelog anywhere so I can get ready for the 3.x upgrade?

**Comment by sandydoo** [comment]
Thanks, @nselikoff. I've added the missing releases.

The main *public* breaking change has to do with [overlays](https://github.com/sandydoo/ember-google-maps/releases/tag/v3.0.0-beta.0).

If you've written any custom map components, then the internals may need updating. No guide here, other than to copy-paste code from one of the standard components.

**Comment by nselikoff** [comment]
Awesome, thanks @sandydoo
