### ISSUE TITLE
Events not registering for Polyline component (v3.0.0-beta.1)

### ISSUE THREAD

**Issue by nselikoff** [sandydoo/ember-google-maps#86]
### Complete this checklist before opening an issue

*Please read the documentation before opening an issue*. Once you understand how this addon works, you will find that most problems can be solved by consulting the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've read the relevant documentation for this addon on [ember-google-maps.sandydoo.me](https://ember-google-maps.sandydoo.me/docs/getting-started).

* [x] I understand how to set options on the components in this addon. Options are not hardcoded. Arguments passed to a component are used to set the options on the map component.

* [x] I've searched the relevant section of the [Google Maps API reference](https://developers.google.com/maps/documentation/javascript/reference/3.exp/).

* [x] I've [searched the closed issues](https://github.com/sandydoo/ember-google-maps/issues?q=is%3Aissue+is%3Aclosed) for similar problems.

--------------------------------------------------------------------------------

### Describe the bug
In v3.0.0-beta.1, events are not properly registered to the polyline component (e.g. `onClick`). This may also apply to other components that override `_didAddComponent`.

### To Reproduce
`{{g.polyline path=path onClick=(action "clickPolyline")}}`

### Expected behaviour
The `clickPolyline` action is called

### Attempted solutions
Overriding `_didAddComponent` in the `Polyline` component seems to be causing this; if you comment out that function so it uses the one from `MapComponent`, the onClick event registers properly.

--------------------------------------------------------------------------------

### Addon configuration and device details

**Addon configuration**:

 - Addon version: 3.0.0-beta.1
 
 - Addon config from `environment.js` (**do not** post your API key): 
 ```
    "ember-google-maps": {
      key: process.env.GOOGLE_MAPS_API_KEY,
      protocol: "https",
      language: "en",
      version: "3.38",

      // default libraries for full mobility widget
      libraries: ["visualization", "places"]
    },
```

 - Google Maps version: 3.38
 
**Desktop:**
 - OS: OS X
 
 - Browser: Chrome
 
 - Version: 79.0.3945.117

**Comment by sandydoo** [comment]
Thanks, @nselikoff! Fixed in new [release](https://github.com/sandydoo/ember-google-maps/releases/tag/v3.0.0-beta.2) with bd49ec1d766fbdaf9e254e19ae534d4ba39fde2f.

**Comment by nselikoff** [comment]
Working well, thanks @sandydoo!
