### ISSUE TITLE
Set map controls position not working

### ISSUE THREAD

**Issue by erzzo** [sandydoo/ember-google-maps#87]
Hi,
I've seen that on my actual project the map controlls changed they're position (to the default one).
I played with it on my local machine and couldn't change the [(controls position)](https://ember-google-maps.sandydoo.me/docs/controls). So I've created a blank project with ember `3.15` and ember google maps `3.0.0-beta.2` but with the same result. Can someone test it if it's working or not?

**Comment by sandydoo** [comment]
Hi, @erzzo,
Yeah, it looks like the map was being created a bit *too* early, before letting Ember update the control position values. Thanks for reporting!

**Comment by erzzo** [comment]
No problem, thank you.

**Comment by erzzo** [comment]
@sandydoo I've tried it with `ember 3.15` (the blank project) and it's working. But with my old one, `ember 3.5`, when the app first loads up, the controls having the default location, then when I transition to a another route and come back, the controls will load up with the right position. Could it be dependent on the ember version?

**Comment by sandydoo** [comment]
> when the app first loads up, the controls having the default location, then when I transition to a another route and come back, the controls will load up with the right position.

That's exactly what I found and fixed. Just checked on `3.4`, `3.5`, `3.6` and `3.15`; couldn't get it to break 🤷‍♂ .

Perhaps there is more going on, but before investigating further, could you double check:
1. Your existing addon is actually using the correct version of the addon `2.2.6` or `3.0.0-beta.3`.
2. Your template has access to the `google` object. So in your controller/component:
```js
import Controller from '@ember/controller';
import { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';

export default Controller.extend({
  googleMapsApi: service(),
  google: reads('googleMapsApi.google')
});
```

**Comment by erzzo** [comment]
Yeah, I have it implemented like u said. Tried both versions, but it's behaving a litle bit strange. On my old project it's setting the right position only by route transition (tried in application.hbs and a subcomponent)

In my blank project it's working only when I call the map in a route template. When I add it to a subcomponent it's setting the wrong controls position.

![image](https://user-images.githubusercontent.com/886192/74189728-37c5e700-4c51-11ea-96d7-784aba6bfb90.png)

the upper map is called from a component (default controls position) the second directly in the application template (correct controls position). Using the same g-map initialization code.

**Comment by sandydoo** [comment]
> the upper map is called from a component

Okay, but does the component also have access to `google`?

```js
import Component from '@ember/component';
import { inject as service } from '@ember/service';
import { reads } from '@ember/object/computed';

export default Component.extend({
  googleMapsApi: service(),
  google: reads('googleMapsApi.google')
});
```

**Comment by erzzo** [comment]
My mistake. I've added the code to the controller not in the component... So it's working with the newer ember, but with my `3.5` still no luck.

**Comment by sandydoo** [comment]
>with my 3.5 still no luck.

Hard to say what's up with the other project. My best and only guess is that it's still somehow using an older version of the addon 🤷‍♂ `npm install` and make sure to restart `ember`?

**Comment by erzzo** [comment]
I've tried to remove all packages, then install them. Checked google maps version - looking good, but still doesn't work. I will probably try to update ember and all packages later, hopefully it will resolve the problem, when not I will spend some more time with this problem

**Comment by erzzo** [comment]
Just for info. After the update to ember 3.17 it started to work
