### ISSUE TITLE
Contextual components in Engines

### ISSUE THREAD

**Issue by jaiivarsson** [sandydoo/ember-google-maps#88]
I'm not sure if this is a bug or limitation in the way the contextual components are dynamically built.

I have an ember-engine that is using this add-on. I have followed the process of including the add-on as a dependancy following the engines guides. The map loads but doesn't return proper instance of the map for the contextual components. In the host application is works perfectly as expected.

This is the snippet in the template is:
```
<GMap @lat={{@latitude}} @lng={{@longitude}} @zoom={{16}} @classNames="w-full h-128 z-below"
   as |g|>
   {{log g}}
  <g.marker
    @lat={{@latitude}}
    @lng={{@longitude}}
    @draggable={{true}}
     />
</GMap>
```

That log line returns the map property as being undefined and all the contextual components, like `marker` are missing. When I see this same snippet in the host application, these properties are all present as expected.

I cloned this repo and spent a lot of time logging the state of the components throughout the process of the apps rendering. As best as I can work out, this add-on's index.js is dynamically injecting the contextual components during the build process. It appears this build tree process isn't run and included when the add-on is included in an engine.

I have wondered if it was possible to copy some of the tree functions into the engine's index.js to get them in there, but thought I'd finally post this before falling down another rabbit hole, in case I'm missing something obvious.

**Comment by sandydoo** [comment]
Hi @jaiivarsson,

Could you try out this branch https://github.com/sandydoo/ember-google-maps/tree/bug-fix-for-engines?

This should work for your `package.json`:
```js
"ember-google-maps": "sandydoo/ember-google-maps#bug-fix-for-engines"
```

**Comment by jaiivarsson** [comment]
Hi @sandydoo ,

Thanks for the quick reply. Unfortunately it didn't changed anything.

Map is still undefined in the template and none of the contextual components are present.

**Comment by sandydoo** [comment]
Strange 🤔 . I've never used engines myself and perhaps you're the first to do so with this addon. The thing is, I did manage to replicate your issue and tested the fix on this test repository. I'm making it public in case it helps you narrow down the issue. https://github.com/sandydoo/ember-google-maps-engine-test

I'd like to get this fixed though. It would be nice to know what versions of everything you are running:
* ember-cli
* ember
* ember-google-maps

**Comment by sandydoo** [comment]
Okay, I may have replicated it again with the latest ember-cli version.

**Comment by sandydoo** [comment]
Alright, I believe this should finally fix it for `ember-cli v3.13+`. https://github.com/sandydoo/ember-google-maps/commit/e4cc079fb3a8a2c860080d85cac50cecf0b54b19 .
Let me know if it works for you.

**Comment by jaiivarsson** [comment]
Yep, that did it. Thank you so much!

In case you're still curious we are running:
- ember-cli 3.15
- ember 3.15
- ember-google-maps 3.0.0-beta.3

**Comment by sandydoo** [comment]
Thanks for reporting this! New releases published.
