### ISSUE TITLE
...attributes not applied to g-map

### ISSUE THREAD

**Issue by knownasilya** [sandydoo/ember-google-maps#91]
Using the latest beta, I can't apply a class like so: `<GMap class='map' @lat='39.113014' @lng='-105.358887' @zoom={{8}} />`.

Looks like `...attributes` isn't added, and the component uses `tagName: ''`.

**Comment by sandydoo** [comment]
Thanks, @knownasilya 👏. I've pushed out a [fix](https://github.com/sandydoo/ember-google-maps/releases/tag/v3.0.0).

**Comment by knownasilya** [comment]
Nice!
