### ISSUE TITLE
Ember Google Maps loading an empty canvas

### ISSUE THREAD

**Issue by puramanuj** [sandydoo/ember-google-maps#93]
After following the readme and guide to get started, I am unable to render the most basic component. It just renders an empty canvas and I dont see any errors/warnings on the browser console.

In looking at the Google Maps API docs, I see that https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap includes invoking a callback. Is this handled internally?

I've pretty much taken the exact steps in the Getting Started guide and can't seem to get past this.

Following are my code changes:

`config/environment.js:`

`'ember-google-maps': {
      key: '<my API key>,
      language: 'en',
      region: 'US',
      protocol: 'https',
      version: 'weekly',
      libraries: ['geometry', 'places']
    }`

CSS changes:
`
.ember-google-map {
  width: 500px;
  height: 300px;
}
`

HBS chnges:
`<GMap lat="51.508530" lng="-0.076132" zoom={{12}} />`

Note: Using Ember octane

**Comment by sandydoo** [comment]
@puramanuj, in Octane, arguments are specified with an `@`. What your code does is set `lat`, `lng`, and `zoom` as html attributes.

```hbs
<GMap @lat="51.508530" @lng="-0.076132" @zoom={{12}} />
```

More info:
https://guides.emberjs.com/release/components/component-arguments-and-html-attributes/

**Comment by puramanuj** [comment]
Hi @sandydoo thanks for the quick update that did work by just adding @, I am still learning Ember Octane,
