### ISSUE TITLE
Issue with packaging addon-test-support 

### ISSUE THREAD

**Issue by bgolla** [sandydoo/ember-google-maps#96]
### Describe the bug
- addon-test-support folder missing on upgrading to 3.0.x version
- But when I use tag in my `package.json` it's working fine
> `./package.json`  
  "ember-google-maps": "https://github.com/sandydoo/ember-google-maps.git#v3.0.5",

### To Reproduce
- Write acceptance tests in v2.2.7
  > ```import { setupMapTest } from 'ember-google-maps/test-support';```
- Upgrade ember-google-maps to 3.0.0 or above
     > `./package.json`  
         "ember-google-maps": "^3.0.5",

### Expected behaviour
- `node_modules/ember-google-maps/addon-test-support` folder should exists
- Tests should run with out any issues.

### Attempted solutions
- `node_modules/ember-google-maps/addon-test-support` folder does not exists
- Tests failure.

**Comment by sandydoo** [comment]
Thanks, @bgolla! New release is out.
