### ISSUE TITLE
The use of the private {{-in-element}} is deprecated

### ISSUE THREAD

**Issue by basz** [sandydoo/ember-google-maps#98]
With ember 3.20 (possibly earlier) I'm getting a deprecation warning

```
DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-google-maps/templates/components/g-map/overlay.hbs' @ L2:C2)  [deprecation id: glimmer.private-in-element]
```

due to

`https://github.com/sandydoo/ember-google-maps/blob/main/addon/templates/components/g-map/overlay.hbs#L2`

**Comment by sandydoo** [comment]
Thanks, @basz! [I've upgrade to addon to use the new public `in-element`.](https://github.com/sandydoo/ember-google-maps/releases/tag/v3.2.0)
