### ISSUE TITLE
Autocomplete stops working on subsequent route visits

### ISSUE THREAD

**Issue by riklaunim** [sandydoo/ember-google-maps#99]
I'm using Google maps with autocomplete on one route and if I go out to some other higher route and then go back the map is back again as it should be but the autocomplete events seems to not fire when I type the address. Looking at the DOM shows that there is no cleanup done:

https://i.imgur.com/BHBFZl7.png

There will be a "pac-container" for every entry to that route and the DIV will persist. Also the script tag has an event. I tried removing listeners in willDestroyElement but that didn't help either (no errors in any case):
```
async willDestroyElement() {
    let google = await this.google;
    google.maps.event.removeListener(this.listener);
    google.maps.event.clearInstanceListeners(this.autocomplete);
    $('.pac-container').remove();
    this._super(...arguments);
  },
```
Is there some solution for this?

**Comment by sandydoo** [comment]
Hi, @riklaunim!
Would you mind posting a reproduction of your issue? I can't seem to reproduce what you're describing.

Regarding the `pac-container`s, there's still no official way of cleaning them up. Not much I can do about that, unfortunately.

**Comment by riklaunim** [comment]
I have it as a part of bigger app but it looks like so:

```
- / 
- /wizard/step1/ 
```
If I go from / to step1 it works fine, but if I use a transition to / from step1 and then back to step1 it does not (standard ember route actions and transitions).

The "step1" has a form and the map

```
{{venue/google-map changeset=@changeset .....}}
```

The component handles the map and blocks/unblock form fields when address is given (that's not related to the autocomplete stuff), the core is like so:
```
  googleMapsApi: service(),
  classNames: ['google-map'],
  google: reads('googleMapsApi.google'),
  init() {
    this._super(...arguments);
    this.markerCoords = null;
    this.mapCoords = {
      zoom: 2,
      lat: 51,
      lng: 21,
    };
    this.registerGoogleAutocomplete();
  },
  async registerGoogleAutocomplete() {
    let google = await this.google;
    let autocomplete = new google.maps.places.Autocomplete(
      (document.querySelector('#autocomplete')),
    );
    this.setAndDisableAddressInputs();
    autocomplete.addListener('place_changed',
      () => this.onMapsPlaceChanged(autocomplete));
  },


  async onMapsPlaceChanged(autocomplete) {
    let place = autocomplete.getPlace();
    place && await this.handlePlace(place);
    this.enableInputs();
  },
```
On first entry the "registerGoogleAutocomplete" get's called and when I type an address the event "onMapsPlaceChanged" also triggers when I type something and pick an autocomplete option. On subsequent entry the "registerGoogleAutocomplete" also is executed while while typing an  address there is no autocomplete and thus no "onMapsPlaceChanged" (and no errors)

The template:
```
<GMap @zoom={{mapCoords.zoom}} @lat={{mapCoords.lat}} @lng={{mapCoords.lng}} @scrollwheel={{true}} @draggable={{true}} @mapTypeControl={{false}} @streetViewControl={{false}} @fullscreenControl={{false}} as |g|>
  <input id="autocomplete" placeholder={{t "wizard.autocomplete"}} type="text">
  {{g.canvas}}
  {{#if markerCoords}}
    <g.marker @lat={{markerCoords.lat}} @lng={{markerCoords.lng}} @draggable={{false}} />
  {{/if}}
</GMap>
```

**Comment by sandydoo** [comment]
Try running `registerGoogleAutocomplete` using the `onLoad` hook on the map.

```hbs
```

**Comment by sandydoo** [comment]
I've released a beta version that improves the way the optional `canvas` component works. It might fix your situation for now.

```
ember install ember-google-maps@beta
```

This is essentially a race condition. You're trying to fetch a DOM element that might or might not be rendered. The fix in the beta version removes a second render pass, which unfortunately recreated your input field after the autocomplete was created.

In general though, running DOM fetching operations on `init` and/or in an async function is not safe.
The safer options are:

1. Use [render modifiers](https://github.com/emberjs/ember-render-modifiers).
```hbs
<input  type="text" {{did-insert this.registerGoogleAutocomplete}}>
```

2. Create a custom autocomplete component by extending the `MapComponent` class. Make sure to use `didInsertElement` and not `init`; or use render modifiers, depending on which Ember version you're on.   Name the component `g-map-addons/<insert name here>` and it will show up along with the other components within `g-map`.
As an example, see https://github.com/sandydoo/ember-google-maps/blob/main/addon/components/g-map/autocomplete.js.

3. Use the `onLoad` hook on `g-map`, which pretty much guarantees that everything is rendered.

**Comment by riklaunim** [comment]
Will check it out.

**Comment by riklaunim** [comment]
I've use the new version (and used didInsertElement) and it works now. Thanks for the help.

**Comment by sandydoo** [comment]
Thanks for reporting this, @riklaunim!
